version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1
    working_directory: /go/src/github.com/thomasobenaus/sokar
    steps:
      - checkout
      - run: make all
      - run: make cover-upload
  service-test:
    machine:
      image: circleci/classic:201808-01
    working_directory: /home/circleci/.go_workspace/src/github.com/thomasobenaus/sokar
    steps:
      - checkout
      - run: make docker.build
      - run: make test.service
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - service-test:
          requires:
            - build
