sca:
  nomad:
    server-address: "http://192.168.0.236:4646"
scale-object:
  name: "fail-service"
  min: 1
  max: 10
saa:
  scale-alerts:
    - name: "AlertA"
      weight: 1.5
    - name: "AlertB"
      weight: -1.5
